/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import ASYS.Main;

/**
 *
 * @author xeon
 */
public class MainASYS extends javax.swing.JFrame {
    Main main;
    /**
     * Creates new form Login
     */
    public MainASYS(Main main) {
        initComponents();
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        NumerosComplejos = new javax.swing.JLabel();
        SeriesFourier = new javax.swing.JLabel();
        logoTecNM = new javax.swing.JLabel();
        lbASYSC = new javax.swing.JLabel();
        bgLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setForeground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumerosComplejos.setBackground(new java.awt.Color(0, 0, 0));
        NumerosComplejos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tema1_NumerosComplejos-small.png"))); // NOI18N
        NumerosComplejos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NumerosComplejos.setOpaque(true);
        NumerosComplejos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NumerosComplejosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NumerosComplejosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NumerosComplejosMouseExited(evt);
            }
        });
        bg.add(NumerosComplejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 130, 90));

        SeriesFourier.setBackground(new java.awt.Color(0, 0, 0));
        SeriesFourier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        SeriesFourier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeriesFourier.setOpaque(true);
        SeriesFourier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SeriesFourierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SeriesFourierMouseExited(evt);
            }
        });
        bg.add(SeriesFourier, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 120, 90));

        logoTecNM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo itess-blanco new-small.png"))); // NOI18N
        bg.add(logoTecNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 210, 80));

        lbASYSC.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbASYSC.setForeground(new java.awt.Color(255, 71, 0));
        lbASYSC.setText("2023 ITESS-TICS ASYS");
        lbASYSC.setToolTipText("");
        bg.add(lbASYSC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 330, 40));

        bgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_logo_gray2.png"))); // NOI18N
        bg.add(bgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 364, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 820, 508);
    }// </editor-fold>//GEN-END:initComponents

    private void NumerosComplejosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumerosComplejosMouseEntered
        NumerosComplejos.setBackground(Color.yellow);
    }//GEN-LAST:event_NumerosComplejosMouseEntered

    private void NumerosComplejosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumerosComplejosMouseExited
        NumerosComplejos.setBackground(Color.black);
    }//GEN-LAST:event_NumerosComplejosMouseExited

    private void SeriesFourierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeriesFourierMouseEntered
        SeriesFourier.setBackground(Color.yellow);
    }//GEN-LAST:event_SeriesFourierMouseEntered

    private void SeriesFourierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeriesFourierMouseExited
        SeriesFourier.setBackground(Color.black);
    }//GEN-LAST:event_SeriesFourierMouseExited

    private void NumerosComplejosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumerosComplejosMouseClicked
        // TODO add your handling code here:
        main.mainASYS.setVisible(false);
        main.complexNumbersASYS.setVisible(true);        
    }//GEN-LAST:event_NumerosComplejosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainASYS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainASYS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumerosComplejos;
    private javax.swing.JLabel SeriesFourier;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgLogo;
    private javax.swing.JLabel lbASYSC;
    private javax.swing.JLabel logoTecNM;
    // End of variables declaration//GEN-END:variables
}
